services:
  - type: web
    plan: free
    name: cloud-render-app
    runtime: node
    repo: https://github.com/tavananh95/cloud-render-test.git
    buildCommand: 'npm install'
    startCommand: 'npm start'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-render-db
          property: connectionString

databases:
  - name: cloud-render-db
    plan: free